</$objtype/mkfile
BIN=/$objtype/bin

TARG=timeline\
	ticker

HFILES=json.h

OFILES=\
	json.$O\
	ticker.$O\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=/386/bin/%}\

</sys/src/cmd/mkmany

all:V:

nuke:V:
	rm -f *.[$OS] [$OS].$TARG $TARG

$O.ticker: ticker.$O json.$O urlencode.$O
	$LD -o $target $prereq

$O.timeline: timeline.$O json.$O
	$LD -o $target $prereq
