#!/bin/sh
cd $HOME
export PLAN9=/usr/local/plan9
export PATH=$PATH:$PLAN9/bin
export font=$PLAN9/font/lucm/unicode.9.font

killall -s plumber >/dev/null 2>&1
if [ "$?" -eq 1 ]; then
	$PLAN9/bin/plumber &
fi

SHELL=rc /usr/local/plan9/bin/9term -W600x700 &
